export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const SORT_FILTER = "SORT_FILTER";
export const FETCH_FILTER_PRODUCTS = "FETCH_FILTER_PRODUCTS";
export const FILTER_PRODUCTS_BY_SIZE = "FILTER_PRODUCTS_BY_SIZE";
export const FILTER_PRODUCTS_BY_COLOR = "FILTER_PRODUCTS_BY_COLOR";
export const FILTER_PRODUCTS_BY_MATERIAL = "FILTER_PRODUCTS_BY_MATERIAL";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";